//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceIntelligence.WebService.WebServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSysConfig", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getSysConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSysDic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getSysDic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDepartmentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getDepartmentInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlarmInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getAlarmInfo(string deptName, string type, string beginTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlarmTypeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getAlarmTypeInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlarmPolice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getAlarmPolice(string alarmID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCallInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getCallInfo(string policeID, string stid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServiceDic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getServiceDic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGPSRealTimeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getGPSRealTimeInfo(string GPSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServiceStatic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getServiceStatic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGPSListTrackHis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getGPSListTrackHis(string deptID, string name, string beginTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGPSTrackLineBack", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getGPSTrackLineBack(string deptID, string beginTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGPSTrackHis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getGPSTrackHis(string gpssimcard, string beginTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPatrolZone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getPatrolZone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPatrolPoint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getPatrolPoint();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPoliceCrossing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getPoliceCrossing(int interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getAuth(string policeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCallInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable setCallInfo(string isresponse, string isconfirm, string frequency, string stid, string jyname, string depname, string jyid, string depid, string username, string userid, string userdepname, string userdepid, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setServiceState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable setServiceState(string stateid, string statenm, string jyid, string statusdes, string username, string gpsTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setAlarmFocus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string setAlarmFocus(string JQID, string ISMUST);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setAlarmPolice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable setAlarmPolice(string JQID, string JYID, string Content, string UpdateUser, string Memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAlarmPolice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable deleteAlarmPolice(string JQID, string JYID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setAlarmPoliceType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string setAlarmPoliceType(string JQID, string JYID, string pTYPE, string UpdateUser, string Memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setAlarmPos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string setAlarmPos(string JQID, string X, string Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCrossRoad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getCrossRoad(string road);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCrossPoint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getCrossPoint(string road1, string road2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addressLocator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable addressLocator(string adddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getExceptService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getExceptService(string deptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWarningArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getWarningArea(string deptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNewTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getNewTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNewTaskPolice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getNewTaskPolice(string taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ErrorRoad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string ErrorRoad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlarmInfoFX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getAlarmInfoFX(string deptName, string typeid, string beginTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlarmTypeInfoFX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getAlarmTypeInfoFX();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBaseSTIDDMG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getBaseSTIDDMG();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setAlarmNewType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string setAlarmNewType(string JQID, string NEWJQLB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getElePolice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getElePolice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCallInfo_Today", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getCallInfo_Today();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCallInfoPT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable setCallInfoPT(
                    string isresponse, 
                    string isconfirm, 
                    string frequency, 
                    string stid, 
                    string jyname, 
                    string depname, 
                    string jyid, 
                    string depid, 
                    string username, 
                    string userid, 
                    string userdepname, 
                    string userdepid, 
                    string note, 
                    string kind, 
                    string position, 
                    string trueName, 
                    string trueKind, 
                    string truePosition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : PoliceIntelligence.WebService.WebServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<PoliceIntelligence.WebService.WebServiceReference.ServiceSoap>, PoliceIntelligence.WebService.WebServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable getSysConfig() {
            return base.Channel.getSysConfig();
        }
        
        public System.Data.DataTable getSysDic() {
            return base.Channel.getSysDic();
        }
        
        public System.Data.DataTable getDepartmentInfo() {
            return base.Channel.getDepartmentInfo();
        }
        
        public System.Data.DataTable getAlarmInfo(string deptName, string type, string beginTime, string endTime) {
            return base.Channel.getAlarmInfo(deptName, type, beginTime, endTime);
        }
        
        public System.Data.DataTable getAlarmTypeInfo() {
            return base.Channel.getAlarmTypeInfo();
        }
        
        public System.Data.DataTable getAlarmPolice(string alarmID) {
            return base.Channel.getAlarmPolice(alarmID);
        }
        
        public System.Data.DataTable getCallInfo(string policeID, string stid) {
            return base.Channel.getCallInfo(policeID, stid);
        }
        
        public System.Data.DataTable getServiceDic() {
            return base.Channel.getServiceDic();
        }
        
        public System.Data.DataTable getGPSRealTimeInfo(string GPSID) {
            return base.Channel.getGPSRealTimeInfo(GPSID);
        }
        
        public System.Data.DataTable getServiceStatic() {
            return base.Channel.getServiceStatic();
        }
        
        public System.Data.DataTable getGPSListTrackHis(string deptID, string name, string beginTime, string endTime) {
            return base.Channel.getGPSListTrackHis(deptID, name, beginTime, endTime);
        }
        
        public System.Data.DataTable getGPSTrackLineBack(string deptID, string beginTime, string endTime) {
            return base.Channel.getGPSTrackLineBack(deptID, beginTime, endTime);
        }
        
        public System.Data.DataTable getGPSTrackHis(string gpssimcard, string beginTime, string endTime) {
            return base.Channel.getGPSTrackHis(gpssimcard, beginTime, endTime);
        }
        
        public System.Data.DataTable getPatrolZone() {
            return base.Channel.getPatrolZone();
        }
        
        public System.Data.DataTable getPatrolPoint() {
            return base.Channel.getPatrolPoint();
        }
        
        public System.Data.DataTable getPoliceCrossing(int interval) {
            return base.Channel.getPoliceCrossing(interval);
        }
        
        public System.Data.DataTable getAuth(string policeID) {
            return base.Channel.getAuth(policeID);
        }
        
        public System.Data.DataTable setCallInfo(string isresponse, string isconfirm, string frequency, string stid, string jyname, string depname, string jyid, string depid, string username, string userid, string userdepname, string userdepid, string note) {
            return base.Channel.setCallInfo(isresponse, isconfirm, frequency, stid, jyname, depname, jyid, depid, username, userid, userdepname, userdepid, note);
        }
        
        public System.Data.DataTable setServiceState(string stateid, string statenm, string jyid, string statusdes, string username, string gpsTime) {
            return base.Channel.setServiceState(stateid, statenm, jyid, statusdes, username, gpsTime);
        }
        
        public string setAlarmFocus(string JQID, string ISMUST) {
            return base.Channel.setAlarmFocus(JQID, ISMUST);
        }
        
        public System.Data.DataTable setAlarmPolice(string JQID, string JYID, string Content, string UpdateUser, string Memo) {
            return base.Channel.setAlarmPolice(JQID, JYID, Content, UpdateUser, Memo);
        }
        
        public System.Data.DataTable deleteAlarmPolice(string JQID, string JYID) {
            return base.Channel.deleteAlarmPolice(JQID, JYID);
        }
        
        public string setAlarmPoliceType(string JQID, string JYID, string pTYPE, string UpdateUser, string Memo) {
            return base.Channel.setAlarmPoliceType(JQID, JYID, pTYPE, UpdateUser, Memo);
        }
        
        public string setAlarmPos(string JQID, string X, string Y) {
            return base.Channel.setAlarmPos(JQID, X, Y);
        }
        
        public System.Data.DataTable getCrossRoad(string road) {
            return base.Channel.getCrossRoad(road);
        }
        
        public System.Data.DataTable getCrossPoint(string road1, string road2) {
            return base.Channel.getCrossPoint(road1, road2);
        }
        
        public System.Data.DataTable addressLocator(string adddress) {
            return base.Channel.addressLocator(adddress);
        }
        
        public System.Data.DataTable getExceptService(string deptID) {
            return base.Channel.getExceptService(deptID);
        }
        
        public System.Data.DataTable getWarningArea(string deptID) {
            return base.Channel.getWarningArea(deptID);
        }
        
        public System.Data.DataTable getNewTask() {
            return base.Channel.getNewTask();
        }
        
        public System.Data.DataTable getNewTaskPolice(string taskID) {
            return base.Channel.getNewTaskPolice(taskID);
        }
        
        public string ErrorRoad() {
            return base.Channel.ErrorRoad();
        }
        
        public System.Data.DataTable getAlarmInfoFX(string deptName, string typeid, string beginTime, string endTime) {
            return base.Channel.getAlarmInfoFX(deptName, typeid, beginTime, endTime);
        }
        
        public System.Data.DataTable getAlarmTypeInfoFX() {
            return base.Channel.getAlarmTypeInfoFX();
        }
        
        public System.Data.DataTable getBaseSTIDDMG() {
            return base.Channel.getBaseSTIDDMG();
        }
        
        public string setAlarmNewType(string JQID, string NEWJQLB) {
            return base.Channel.setAlarmNewType(JQID, NEWJQLB);
        }
        
        public System.Data.DataTable getElePolice() {
            return base.Channel.getElePolice();
        }
        
        public System.Data.DataTable getCallInfo_Today() {
            return base.Channel.getCallInfo_Today();
        }
        
        public System.Data.DataTable setCallInfoPT(
                    string isresponse, 
                    string isconfirm, 
                    string frequency, 
                    string stid, 
                    string jyname, 
                    string depname, 
                    string jyid, 
                    string depid, 
                    string username, 
                    string userid, 
                    string userdepname, 
                    string userdepid, 
                    string note, 
                    string kind, 
                    string position, 
                    string trueName, 
                    string trueKind, 
                    string truePosition) {
            return base.Channel.setCallInfoPT(isresponse, isconfirm, frequency, stid, jyname, depname, jyid, depid, username, userid, userdepname, userdepid, note, kind, position, trueName, trueKind, truePosition);
        }
    }
}
